//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParserCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AttrExpr {
            get {
                object obj = ResourceManager.GetObject("AttrExpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MsgExpr {
            get {
                object obj = ResourceManager.GetObject("MsgExpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NameExpr {
            get {
                object obj = ResourceManager.GetObject("NameExpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NxGrammar {
            get {
                object obj = ResourceManager.GetObject("NxGrammar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ObjExpr {
            get {
                object obj = ResourceManager.GetObject("ObjExpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OperExpr {
            get {
                object obj = ResourceManager.GetObject("OperExpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RoleExpr {
            get {
                object obj = ResourceManager.GetObject("RoleExpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransExpr {
            get {
                object obj = ResourceManager.GetObject("TransExpr", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
